### ISSUE TITLE
Parameter didn't pass correctly

### ISSUE THREAD

**Issue by danielchen76** [hirotakaster/CoAP-simple-library#12]
https://github.com/hirotakaster/CoAP-simple-library/blob/f3ab245bca215516f14849cc6ca61d744e9d7f3c/coap-simple.cpp#L123

Need pass type, method, token,tokenlen to send function.
`
uint16_t Coap::send(IPAddress ip, int port, char *url, COAP_TYPE type, COAP_METHOD method, uint8_t *token, uint8_t tokenlen, uint8_t *payload, uint32_t payloadlen) {
    return this->send(ip, port, url, type, method, token, tokenlen, (uint8_t *)payload, payloadlen, COAP_NONE);
}
`

**Comment by mengguang** [comment]
+1

**Comment by hirotakaster** [comment]
close  #13
