### ISSUE TITLE
Use GitHub actions to test CoAP-simple-library on multiple platforms

### ISSUE THREAD

**Issue by jackjansen** [hirotakaster/CoAP-simple-library#23]
Hi, would you be interested in using the GitHub Actions CI/CD to automatically test (compilation only) CoAP-simple-library?

I'm investigating it at the moment for my own projects, to do builds with both PlatformIO and Arduino, for multiple architectures. 

If you're interested I could experiment with a fork of CoAP-simple-library in stead of with the Blink project (as I'm doing now) and I could give you a pull request when/if I get something working...

**Comment by hirotakaster** [comment]
@jackjansen 
Hi, It's nice idea. I think this library support target is Arduino/ESP8266/ESP32 with Arduino IDE/PIO. 
And I will try Github Actions CI/CD by own.

**Comment by jackjansen** [comment]
Wonderful!
In case you're interested: my playground is at https://github.com/jackjansen/cicdtest which builds the blink app for 3 platforms using both Arduino and PlatformIO.

**Comment by hirotakaster** [comment]
I add arduno-cli(avr/esp32) workflow. I will add pio workflow later.

**Comment by jackjansen** [comment]
You're using completely different arduino-cli setup than I was experimenting with. Yours looks a lot more promising for libraries (the `ArminJo/arduino-test-compile` I was using seems more geared towards programs than libraries with examples. Thanks!

**Comment by hirotakaster** [comment]
@jackjansen Ah, I find your workflow now, your pattern LGTM. I will use your workflow.

**Comment by hirotakaster** [comment]
Thank you!! everything works well.

**Comment by hirotakaster** [comment]
@jackjansen thank you for your repo.
