### ISSUE TITLE
URL Query not parsed correctly

### ISSUE THREAD

**Issue by MarianKellerHTWG** [hirotakaster/CoAP-simple-library#37]
A URL with an added query, for example : "ps/sensors/?clientid=test1&retain=true" is parsed incorrectly. The library doesn't detect that the path ends before the question mark, and that the following tokens should be parsed as a UriQuery.

**Comment by YelloooBlue** [comment]
+!

**Comment by YelloooBlue** [comment]
+1

**Comment by YelloooBlue** [comment]
I have fixed this issue, you can view my [fork](https://github.com/YelloooBlue/CoAP-simple-library), I have submitted PR

**Comment by hirotakaster** [comment]
@YelloooBlue 
Thanks for your PR. 
Now I merge and will release new tag(for update to arduino library).
