### ISSUE TITLE
coaptest.ino

### ISSUE THREAD

**Issue by JeanSath** [hirotakaster/CoAP-simple-library#43]
Hello, 

I'm trying to use coaptest.ino using PlatformIO. I want to use the file to do an initial test and see if I can connect with my ESP32. However, when generating the code, I am receiving the following return:

![image](https://github.com/user-attachments/assets/91782041-2a68-4e25-bde1-50a274c83166)

![image](https://github.com/user-attachments/assets/e87faa2b-1b1a-4397-8967-f7c0402cd66a)

How do I resolve this? Do I need to install the Dhcp.h library and the others that are being declared?

**Comment by hirotakaster** [comment]
@JeanSath 
try to use "esp32.ino" sample code. 
ESP32 is not equal to coaptest.

**Comment by hirotakaster** [comment]
@JeanSath 
Yes, and update sample code with AP mode code by own.
enjoy it.

**Comment by JeanSath** [comment]
Hi @hirotakaster!!

Everything is working, the only thing missing is the wifi working. but one step at a time hahah

Have a nice day and thanks for you support :)
